#!/usr/bin/env node
/**
 * build-data.js — Read SQLite articles DB → generate articles-data.js
 * This file is embedded into the GitHub Pages deployment so search works
 * entirely client-side without any server.
 *
 * Usage: node scripts/build-data.js
 */

const initSqlJs = require("sql.js");
const fs = require("fs");
const path = require("path");

const DB_PATH = path.join(__dirname, "..", "data", "wechat-search.db");
const OUTPUT = path.join(__dirname, "..", "articles-data.js");

async function main() {
  if (!fs.existsSync(DB_PATH)) {
    console.error("Database not found at", DB_PATH);
    console.error("Run the server and add articles first.");
    process.exit(1);
  }

  const SQL = await initSqlJs();
  const buffer = fs.readFileSync(DB_PATH);
  const db = new SQL.Database(buffer);

  const res = db.exec(
    "SELECT id, title, summary, keywords, pub_date, article_url, source_name, content FROM articles ORDER BY pub_date DESC"
  );

  const articles = [];
  if (res[0]) {
    const cols = res[0].columns;
    articles.push(...res[0].values.map(v => Object.fromEntries(cols.map((c, i) => [c, v[i] || ""]))));
  }

  // Generate JS file with all articles embedded
  const js = `// Auto-generated by build-data.js — DO NOT EDIT
// Generated at: ${new Date().toISOString()}
// Article count: ${articles.length}
window.__ARTICLES__ = ${JSON.stringify(articles)};
`;

  fs.writeFileSync(OUTPUT, js, "utf-8");
  console.log(`[build-data] Generated articles-data.js with ${articles.length} articles`);
}

main().catch(err => {
  console.error("Fatal:", err);
  process.exit(1);
});
